<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

// The admin invitation email, sent through Grantly's own mailer (Resend) rather than Supabase,
// so both the first send and any resend share one branded template. The link is a Supabase
// invite action link generated by SupabaseAdminService::generateInviteLink().
//
// Deliberately NOT ShouldQueue: an invite/resend is an interactive admin action, so we send it
// inline and surface the outcome immediately, rather than depend on a running queue worker.
class AdminInvite extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(public string $email, public string $inviteUrl)
    {
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "You've been invited to Grantly",
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.admin-invite',
            with: [
                'inviteUrl' => $this->inviteUrl,
            ],
        );
    }
}
